<?php
    return [
        41 => [
            'site_connect'     => 'mysql_azerbaijanimmigration_com',
            'site_name'        => 'azerbaijan',
            'site_domain'      => 'azerbaijanimmigration.com',
            'site_number'      => 1,
            'site_code'        => 'AZ',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@azerbaijanimmigration.com',
                'from_email'   => "noreply@azerbaijanimmigration.org",
                'brand_name'   => 'Azerbaijan Immigration Services Team',
                'site_name'    => 'Azerbaijan',
            ],
        ],
        7  => [
            'site_connect'     => 'mysql_cambodiaimmigration_org',
            'site_name'        => 'cambodia',
            'site_domain'      => 'cambodiaimmigration.org',
            'site_number'      => 2,
            'site_code'        => 'KH',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@cambodiaimmigration.org',
                'from_email'   => "noreply@cambodiaimmigration.org",
                'brand_name'   => 'Cambodia Immigration Services Team',
                'site_name'    => 'Cambodia',
            ],
        ],
        82 => [
            'site_connect'     => 'mysql_ethiopiaimmigration_org',
            'site_name'        => 'ethiopia',
            'site_domain'      => 'ethiopiaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'ET',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@ethiopiaimmigration.org',
                'from_email'   => "noreply@ethiopiaimmigration.org",
                'brand_name'   => 'Ethiopia Immigration Services Team',
                'site_name'    => 'Ethiopia',
            ],
        ],
        54 => [
            'site_connect'     => 'mysql_myanmarimmigration_org',
            'site_name'        => 'myanmar',
            'site_domain'      => 'myanmarimmigration.org',
            'site_number'      => 2,
            'site_code'        => 'MM',
            'date_arrival_utc' => true,
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@myanmarimmigration.org',
                'from_email'   => "noreply@myanmarimmigration.org",
                'brand_name'   => 'Myanmar Immigration Services Team',
                'site_name'    => 'Myanmar',
            ],
        ],
        52 => [
            'site_connect'     => 'mysql_qatarimmigration_org',
            'site_name'        => 'qatar',
            'site_domain'      => 'qatarimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'QA',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@qatarimmigration.org',
                'from_email'   => "noreply@qatarimmigration.org",
                'brand_name'   => 'Qatar Immigration Services Team',
                'site_name'    => 'Qatar',
            ],
        ],
        71 => [
            'site_connect'     => 'mysql_rwandaimmigration_org',
            'site_name'        => 'rwanda',
            'site_domain'      => 'rwandaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'RW',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@rwandaimmigration.org',
                'from_email'   => "noreply@rwandaimmigration.org",
                'brand_name'   => 'Rwanda Immigration Services Team',
                'site_name'    => 'Rwanda',
            ],
        ],
        81 => [
            'site_connect'     => 'mysql_tanzaniaimmigration_org',
            'site_name'        => 'tanzania',
            'site_domain'      => 'tanzaniaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'TZ',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@tanzaniaimmigration.org',
                'from_email'   => "noreply@tanzaniaimmigration.org",
                'brand_name'   => 'Tanzania Immigration Services Team',
                'site_name'    => 'Tanzania',
            ],
        ],
        77 => [
            'site_connect'     => 'mysql_thecanadianimmigration_org',
            'site_name'        => 'canada',
            'site_domain'      => 'thecanadianimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'CA',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@thecanadianimmigration.org',
                'from_email'   => "noreply@thecanadianimmigration.org",
                'brand_name'   => 'Canada Immigration Services Team',
                'site_name'    => 'Canada',
            ],
        ],
        83 => [
            'site_connect'     => 'mysql_uaeimmigration_org',
            'site_name'        => 'uae',
            'site_domain'      => 'uaeimmigration.org',
            'site_number'      => 2,
            'site_code'        => 'AE',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa1@uaeimmigration.org',
                'from_email'   => "noreply@uaeimmigration.org",
                'brand_name'   => 'Uae Immigration Services Team',
                'site_name'    => 'Uae',
            ],
        ],
        55 => [
            'site_connect'     => 'mysql_ugandaimmigration_org',
            'site_name'        => 'uganda',
            'site_domain'      => 'ugandaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'UG',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@ugandaimmigration.org',
                'from_email'   => "noreply@ugandaimmigration.org",
                'brand_name'   => 'Uganda Immigration Services Team',
                'site_name'    => 'Uganda',
            ],
        ],
        49 => [
            'site_connect'     => 'mysql_indianimmigration_org',
            'site_name'        => 'india',
            'site_domain'      => 'indianimmigration.org',
            'site_number'      => 8,
            'site_code'        => 'IN',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@indianimmigration.org',
                'from_email'   => "noreply@indianimmigration.org",
                'brand_name'   => 'India Immigration Services Team',
                'site_name'    => 'India',
            ],
            'date_arrival_utc' => true,
        ],
        50 => [
            'site_connect'     => 'mysql_egyptimmigration_org',
            'site_name'        => 'egypt',
            'site_domain'      => 'egyptimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'EG',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@egyptimmigration.org',
                'from_email'   => "noreply@egyptimmigration.org",
                'brand_name'   => 'Egypt Immigration Services Team',
                'site_name'    => 'Egypt',
            ],
        ],
        87 => [
            'site_connect'     => 'mysql_auimmigration_org',
            'site_name'        => 'australia',
            'site_domain'      => 'auimmigration.org',
            'site_number'      => 4,
            'site_code'        => 'AU',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@auimmigration.org',
                'from_email'   => "noreply@auimmigration.org",
                'brand_name'   => 'Australia Immigration Services Team',
                'site_name'    => 'Australia',
            ],
        ],
        33 => [
            'site_connect'     => 'mysql_kenyaimmigration_org',
            'site_name'        => 'kenya',
            'site_domain'      => 'kenyaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'KE',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@kenyaimmigration.org',
                'from_email'   => "noreply@kenyaimmigration.org",
                'brand_name'   => 'Kenya Immigration Services Team',
                'site_name'    => 'Kenya',
            ]
        ],
        10 => [
            'site_connect'     => 'mysql_srilankaimmigration_org',
            'site_name'        => 'sri-lanka',
            'site_domain'      => 'srilankaimmigration.org',
            'site_number'      => 2,
            'site_code'        => 'LK',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@srilankaimmigration.org',
                'from_email'   => "noreply@srilankaimmigration.org",
                'brand_name'   => 'Sri-lanka Immigration Services Team',
                'site_name'    => 'Sri-lanka',
            ],
        ],
        34 => [
            'site_connect'     => 'mysql_srilankavisa_lk',
            'site_name'        => 'sri-lanka',
            'site_domain'      => 'srilankavisa.lk',
            'site_number'      => 2,
            'site_code'        => 'LK',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@srilankavisa.lk',
                'from_email'   => "noreply@srilankavisa.lk",
                'brand_name'   => 'Sri-lanka Immigration Services Team',
                'site_name'    => 'Sri-lanka',
            ],
        ],
        90 => [
            'site_connect'     => 'mysql_uaevisa_ae',
            'site_name'        => 'uae',
            'site_domain'      => 'uaevisa.ae',
            'site_number'      => 3,
            'site_code'        => 'AE',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@uaevisa.ae',
                'from_email'   => "noreply@uaevisa.ae",
                'brand_name'   => 'Uae Immigration Services Team',
                'site_name'    => 'Uae',
            ],
        ],
        84 => [
            'site_connect'     => 'mysql_ivorycoastimmigration_org',
            'site_name'        => 'ivory-coast',
            'site_domain'      => 'ivorycoastimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'CI',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@ivorycoastimmigration.org',
                'from_email'   => "noreply@ivorycoastimmigration.org",
                'brand_name'   => 'Ivory-coast Immigration Services Team',
                'site_name'    => 'Ivory-coast',
            ],
        ],
        51 => [
            'site_connect'     => 'mysql_kuwaitimmigration_org',
            'site_name'        => 'kuwait',
            'site_domain'      => 'kuwaitimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'KW',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@kuwaitimmigration.org',
                'from_email'   => "noreply@kuwaitimmigration.org",
                'brand_name'   => 'Kuwait Immigration Services Team',
                'site_name'    => 'Kuwait',
            ],
        ],
        76 => [
            'site_connect'     => 'mysql_laoevisa_org',
            'site_name'        => 'laos',
            'site_domain'      => 'laoevisa.org',
            'site_number'      => 1,
            'site_code'        => 'LA',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@laoevisa.org',
                'from_email'   => "noreply@laoevisa.org",
                'brand_name'   => 'Laos Immigration Services Team',
                'site_name'    => 'Laos',
            ],
        ],
        91 => [
            'site_connect'     => 'mysql_newzealandvisaonline_com',
            'site_name'        => 'new zealand',
            'site_domain'      => 'newzealandvisaonline.com',
            'site_number'      => 8,
            'site_code'        => 'NZ',
            'date_arrival_utc' => true,
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@newzealandvisaonline.com',
                'from_email'   => "noreply@newzealandvisaonline.com",
                'brand_name'   => 'New Zealand Immigration Services Team',
                'site_name'    => 'New Zealand',
            ],
        ],
        85 => [
            'site_connect'     => 'mysql_saudiarabiaimmigration_org',
            'site_name'        => 'saudi arabia',
            'site_domain'      => 'saudiarabiaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'SA',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@saudiarabiaimmigration.org',
                'from_email'   => "noreply@saudiarabiaimmigration.org",
                'brand_name'   => 'Saudi arabia Immigration Services Team',
                'site_name'    => 'Saudi arabia',
            ],
        ],
        86 => [
            'site_connect'     => 'mysql_taiwanimmigration_org',
            'site_name'        => 'taiwan',
            'site_domain'      => 'taiwanimmigration.org',
            'site_number'      => 2,
            'site_code'        => 'TW',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@taiwanimmigration.org',
                'from_email'   => "noreply@taiwanimmigration.org",
                'brand_name'   => 'Taiwan Immigration Services Team',
                'site_name'    => 'Taiwan',
            ],
        ],
        43 => [
            'site_connect'     => 'mysql_taiwanimmigration_com_tw',
            'site_name'        => 'taiwan',
            'site_domain'      => 'taiwanimmigration.com.tw',
            'site_number'      => 1,
            'site_code'        => 'TW',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@taiwanimmigration.com.tw',
                'from_email'   => "noreply@taiwanimmigration.com.tw",
                'brand_name'   => 'Taiwan Immigration Services Team',
                'site_name'    => 'Taiwan',
            ],
        ],
        8  => [
            'site_connect'     => 'mysql_turkeyimmigration_org',
            'site_name'        => 'turkey',
            'site_domain'      => 'turkeyimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'TR',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@turkeyimmigration.org',
                'from_email'   => "noreply@turkeyimmigration.org",
                'brand_name'   => 'Turkey Immigration Services Team',
                'site_name'    => 'Turkey',
            ],
        ],
        89 => [
            'site_connect'     => 'mysql_zambianimmigration_org',
            'site_name'        => 'zambia',
            'site_domain'      => 'zambianimmigration.org',
            'site_number'      => 8,
            'site_code'        => 'ZM',
            'date_arrival_utc' => true,
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@zambianimmigration.org',
                'from_email'   => "noreply@zambianimmigration.org",
                'brand_name'   => 'Zambia Immigration Services Team',
                'site_name'    => 'Zambia',
            ],
        ],
        13 => [
            'site_connect'     => 'mysql_thevietnamimmigration_org',
            'site_name'        => 'vietnam',
            'site_domain'      => 'thevietnamimmigration.org',
            'site_number'      => 6,
            'site_code'        => 'VN',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@thevietnamimmigration.org',
                'from_email'   => "noreply@thevietnamimmigration.org",
                'brand_name'   => 'Vietnam Immigration Services Team',
                'site_name'    => 'Vietnam',
            ],
        ],
        39 => [
            'site_connect'     => 'mysql_vietnamvisacorp_com',
            'site_name'        => 'vietnam',
            'site_domain'      => 'vietnamvisacorp.com',
            'site_number'      => 1,
            'site_code'        => 'VN',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@vietnamvisacorp.com',
                'from_email'   => "noreply@vietnamvisacorp.com",
                'brand_name'   => 'Vietnam Immigration Services Team',
                'site_name'    => 'Vietnam',
            ],
        ],
        11 => [
            'site_connect'     => 'mysql_vietnamimmigration_com_au',
            'site_name'        => 'vietnam',
            'site_domain'      => 'vietnamimmigration.com.au',
            'site_number'      => 5,
            'site_code'        => 'VN',
            'site_new_payment' => false,
            'site_info'        => [
                'email_system' => 'visa@vietnamimmigration.com.au',
                'from_email'   => "noreply@vietnamimmigration.com.au",
                'brand_name'   => 'Vietnam Immigration Services Team',
                'site_name'    => 'Vietnam',
            ],
        ],
        6  => [
            'site_connect' => 'mysql_globalvisacorp_com',
            'site_name'    => 'global',
            'site_domain'  => 'globalvisacorp.com',
            'site_number'  => '',
            'site_code'    => 'GX',
        ],
        94 => [
            'site_connect'     => 'mysql_malaysiaimmigration_org',
            'site_name'        => 'malaysia',
            'site_domain'      => 'malaysiaimmigration.org',
            'site_number'      => 1,
            'site_code'        => 'MY',
            'site_new_payment' => true,
            'site_info'        => [
                'email_system' => 'visa@kenyaimmigration.org',
                'from_email'   => "noreply@kenyaimmigration.org",
                'brand_name'   => 'Malaysia Immigration Services Team',
                'site_name'    => 'Malaysia',
            ],
        ],
    ];
?>
